openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8086
    description: Generated server url
paths:
  /api/{postId}/comments:
    get:
      operationId: getComments
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
    post:
      operationId: createComment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentDTO'
      responses:
        "200":
          description: default response
  /api/users:
    get:
      operationId: getAllUser
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        "200":
          description: default response
  /api/posts/{postId}:
    put:
      operationId: likePost
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: default response
  /api/posts/api/{postId}:
    get:
      operationId: getPost
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Post'
  /api/posts:
    get:
      operationId: getPosts
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      operationId: createPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostDTO'
      responses:
        "200":
          description: default response
  /api/users/{userId}:
    get:
      operationId: getUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
    put:
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        "200":
          description: default response
components:
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int32
        message:
          type: string
        publishDate:
          type: string
          format: date-time
        author:
          type: integer
          format: int32
        post:
          type: integer
          format: int32
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        lastName:
          type: string
        firstName:
          type: string
        email:
          type: string
        gender:
          type: string
        dateOfBirth:
          type: string
          format: date
        registerDate:
          type: string
          format: date
    CommentDTO:
      required:
        - author
        - message
      type: object
      properties:
        message:
          type: string
        author:
          type: string
        post:
          type: integer
          format: int32
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int32
        text:
          type: string
        likes:
          type: integer
          format: int32
        publishDate:
          type: string
          format: date-time
        author:
          type: integer
          format: int32
    PostDTO:
      required:
        - author
        - text
      type: object
      properties:
        text:
          type: string
        author:
          type: string
    UserDTO:
      required:
        - dateOfBirth
        - email
        - firstName
        - gender
        - lastName
        - registerDate
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string
        email:
          type: string
        gender:
          type: string
        dateOfBirth:
          type: string
          format: date
        registerDate:
          type: string
          format: date
